#!/usr/bin/env bash
set -e

function help()
{
    cat <<EOF
Select with fzf a workflow from GitHub Actions to view, watch, cancel.
Usage:
  gh fzf-run

Flags:
  -R, --repo OWNER/REPO\tSelect another repository.
  -h, --help\tShow help for command
EOF
}

REPO=""
while [ $# -gt 0 ]; do
    key="$1"
    case ${key} in
        -h|--help)
            help
            exit 0
            ;;
        -R|--repository)
            REPO="$2"
            shift
            ;;
        *)
            PARAMS="${PARAMS} ${1}"
            ;;
    esac
    shift
done
eval set -- "${PARAMS}"
if [ -z "$1" ]; then
    ACTION="view"
else
    ACTION="$1"
fi

REPO_OPT=""
if [ -n "${REPO}" ]; then
    REPO_OPT="-R ${REPO}"
fi

# Check dependencies ar available
if ! type -p fzf >/dev/null; then
  echo "fzf not found on the system" >&2
  exit 1
fi

wf_sel=$(gh run ${REPO_OPT} list | fzf -m | jq -r -R -s 'split("\n") | [ .[] | select(length > 0)]')
wf_sel_id="$(echo "${wf_sel}" | jq -r ".[] | split(\"\t\") | [.[] | select(length > 0)] | .[-3]")"
for wf_id in ${wf_sel_id}; do
    gh run ${REPO_OPT} ${ACTION} ${wf_id}
done
