#!/usr/bin/env bash
set -e

function help()
{
    cat <<EOF
Select with fzf a workflow from GitHub Actions to view, watch, cancel.
Usage:
  gh fzf-run [action]

Actions:
  Any actions supported by 'gh run' which takes a workflow id as parameter

Flags:
  -R, --repo OWNER/REPO\tSelect another repository.
  -b, --branch\tFilter runs by branch
  -w, --workflow\tFilter runs by workflow (Use yaml filename if the name contains space)
  -h, --help\tShow help for command
EOF
}

REPO=""
LIST_OPT=()
while [ $# -gt 0 ]; do
    key="$1"
    case ${key} in
        -h|--help)
            help
            exit 0
            ;;

        -b|--branch)
            LIST_OPT+=(--branch "$2")
            shift
            ;;
        -w|--workflow)
            # Cannot use workflow name with spaces, must use yml filename.
            LIST_OPT+=(--workflow "$2")
            shift
            ;;
        -R|--repository)
            REPO="$2"
            shift
            ;;
        *)
            PARAMS="${PARAMS} ${1}"
            ;;
    esac
    shift
done
eval set -- "${PARAMS}"
if [ -z "$1" ]; then
    ACTION="view"
else
    ACTION="$1"
fi

REPO_OPT=""
if [ -n "${REPO}" ]; then
    REPO_OPT="-R ${REPO}"
fi
export REPO_OPT
RUN_OPT="${REPO_OPT}"

# Check dependencies are available
if ! type -p fzf >/dev/null; then
  echo "fzf not found on the system" >&2
  exit 1
fi

JSON_FIELDS="status,conclusion,displayTitle,workflowName,headBranch,event,createdAt,databaseId"
TITLES="[\"STATUS\", \"CONCLUSION\", \"WORKFLOW\", \"TITLE\", \"BRANCH\", \"EVENT\", \"TIMESTAMP\", \"ID\"]"
FIELDS="[.status, .conclusion, .workflowName, .displayTitle, .headBranch, .event, .createdAt, .databaseId]"
COMPLETED_JQUERY="(${TITLES}), (.[] | [select(.status | test(\"completed\"))] | (.[] | ${FIELDS})) | @tsv"
NOT_COMPLETED_JQUERY="(${TITLES}), (map (select(.conclusion ==\"\").conclusion=\"inprogress\") | .[] | [select(.status | test(\"completed\") | not)] | (.[] | ${FIELDS})) | @tsv"
STATUS_ANY_JQUERY="(${TITLES}), (map (select(.conclusion ==\"\").conclusion=\"inprogress\") | .[] | (${FIELDS})) | @tsv"
export JSON_FIELDS

case ${ACTION} in
    cancel|watch)
        QUERY="${NOT_COMPLETED_JQUERY}"
        ;;
    delete|download|rerun)
        QUERY="${COMPLETED_JQUERY}"
        ;;
    view)
        QUERY="${STATUS_ANY_JQUERY}"
        ;;
    *)
        echo "Unknown action ${ACTION}"
        exit 1
esac
export QUERY
LIST_OPT+=(--json ${JSON_FIELDS})
export LIST_OPT
list_opt="${LIST_OPT[@]}"
export list_opt
wf_sel=$(gh run ${REPO_OPT} list "${LIST_OPT[@]}" --jq "${QUERY}" | column -ts $'\t' | fzf -0 --bind 'ctrl-r:reload(gh run ${REPO_OPT} list ${list_opt} --jq "${QUERY}" | column -ts $'"'"'\t'"'"')' --header-lines=1 --multi | jq -r -R -s 'split("\n") | [ .[] | select(length > 0)]')
wf_sel_ids="$(echo "${wf_sel}" | jq -r '.[] | split(" ") | [.[] | select(length > 0)] | .[-1]')"
for wf_id in ${wf_sel_ids}; do
    gh run ${REPO_OPT} ${ACTION} ${wf_id}
done
